/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myNfTsSol from "./myNFTs.sol";
export type { myNfTsSol };
export type { Lock } from "./Lock";
